# Generated by Django 4.2.7 on 2023-12-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_rename_datetime_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', '-created_at']},
        ),
    ]
