# Generated by Django 4.2.7 on 2023-12-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', 'created_at']},
        ),
    ]
